### ISSUE TITLE
New site request: hangouts

### ISSUE THREAD

**Issue by erasche** [tobykurien/GoogleApps#21] opened 2015-10-19 05:54 UTC
It would be very helpful if hangouts was added to the list of supported URLs. (https://hangouts.google.com)

thanks!

**Comment by tobykurien** [comment] 2015-10-20 06:40
That site just re-directs to the app on Play Store. As far as I can see, there is no hangouts mobi site.

**Comment by tobykurien** [comment] 2015-10-20 06:41
Also, duplicate of this: https://github.com/tobykurien/GoogleApps/issues/18

**Closed by tobykurien** 2015-10-20 06:41 UTC

**Comment by erasche** [comment] 2015-10-20 14:41
Okay, thanks.
